/*
 * generated by Xtext 2.15.0-SNAPSHOT
 */
package org.xtext.example.mydsl.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AlternativeAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.GroupAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import org.xtext.example.mydsl.services.TURNGrammarAccess;

@SuppressWarnings("all")
public class TURNSyntacticSequencer extends AbstractSyntacticSequencer {

	protected TURNGrammarAccess grammarAccess;
	protected AbstractElementAlias match_AndFork_EndPoint_FailurePoint_Timer_WaitingPlace_FailKeyword_0_or_WaitKeyword_1_or___AndKeyword_0_LeftCurlyBracketKeyword_2_RightCurlyBracketKeyword_4___or___EndKeyword_0_FullStopKeyword_3___or___TimerKeyword_1_LeftCurlyBracketKeyword_3_TimeoutKeyword_4_q_RightCurlyBracketKeyword_7__;
	protected AbstractElementAlias match_AndFork_FailurePoint_Timer_WaitingPlace___FailKeyword_0_or_WaitKeyword_1_or___AndKeyword_0_LeftCurlyBracketKeyword_2_RightCurlyBracketKeyword_4___or___TimerKeyword_1_LeftCurlyBracketKeyword_3_TimeoutKeyword_4_q_RightCurlyBracketKeyword_7____q;
	protected AbstractElementAlias match_AndJoin_SyncKeyword_0_1_or_SynchKeyword_0_0_or_VerticalLineKeyword_0_2;
	protected AbstractElementAlias match_ComponentRef_ProtectedKeyword_0_q;
	protected AbstractElementAlias match_Condition___LeftCurlyBracketKeyword_3_0_RightCurlyBracketKeyword_3_2__q;
	protected AbstractElementAlias match_ContributionContext_IncludesKeyword_5_0_q;
	protected AbstractElementAlias match_EvaluationStrategy___IncludesKeyword_6_0_LeftCurlyBracketKeyword_6_1_RightCurlyBracketKeyword_6_3__q;
	protected AbstractElementAlias match_FailurePoint_Timer_WaitingPlace_FailKeyword_0_or_WaitKeyword_1_or___TimerKeyword_1_LeftCurlyBracketKeyword_3_TimeoutKeyword_4_q_RightCurlyBracketKeyword_7__;
	protected AbstractElementAlias match_PathWithReferencedEnd_SemicolonKeyword_1_1_q;
	protected AbstractElementAlias match_Stub___LeftCurlyBracketKeyword_4_0_RightCurlyBracketKeyword_4_2__q;
	protected AbstractElementAlias match_Timer_TimeoutKeyword_4_q;
	protected AbstractElementAlias match_Timer_WaitingPlace_WaitKeyword_1_or___TimerKeyword_1_LeftCurlyBracketKeyword_3_TimeoutKeyword_4_q_RightCurlyBracketKeyword_7__;
	protected AbstractElementAlias match_URNspec___MetadataKeyword_11_0_LeftCurlyBracketKeyword_11_1_RightCurlyBracketKeyword_11_3__a;
	protected AbstractElementAlias match_URNspec___MetadataKeyword_11_0_LeftCurlyBracketKeyword_11_1_RightCurlyBracketKeyword_11_3__p;
	protected AbstractElementAlias match_URNspec___RightCurlyBracketKeyword_11_3_MetadataKeyword_11_0_LeftCurlyBracketKeyword_11_1__a;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (TURNGrammarAccess) access;
		match_AndFork_EndPoint_FailurePoint_Timer_WaitingPlace_FailKeyword_0_or_WaitKeyword_1_or___AndKeyword_0_LeftCurlyBracketKeyword_2_RightCurlyBracketKeyword_4___or___EndKeyword_0_FullStopKeyword_3___or___TimerKeyword_1_LeftCurlyBracketKeyword_3_TimeoutKeyword_4_q_RightCurlyBracketKeyword_7__ = new AlternativeAlias(false, false, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getAndForkAccess().getAndKeyword_0()), new TokenAlias(false, false, grammarAccess.getAndForkAccess().getLeftCurlyBracketKeyword_2()), new TokenAlias(false, false, grammarAccess.getAndForkAccess().getRightCurlyBracketKeyword_4())), new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getEndPointAccess().getEndKeyword_0()), new TokenAlias(false, false, grammarAccess.getEndPointAccess().getFullStopKeyword_3())), new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getTimerAccess().getTimerKeyword_1()), new TokenAlias(false, false, grammarAccess.getTimerAccess().getLeftCurlyBracketKeyword_3()), new TokenAlias(false, true, grammarAccess.getTimerAccess().getTimeoutKeyword_4()), new TokenAlias(false, false, grammarAccess.getTimerAccess().getRightCurlyBracketKeyword_7())), new TokenAlias(false, false, grammarAccess.getFailurePointAccess().getFailKeyword_0()), new TokenAlias(false, false, grammarAccess.getWaitingPlaceAccess().getWaitKeyword_1()));
		match_AndFork_FailurePoint_Timer_WaitingPlace___FailKeyword_0_or_WaitKeyword_1_or___AndKeyword_0_LeftCurlyBracketKeyword_2_RightCurlyBracketKeyword_4___or___TimerKeyword_1_LeftCurlyBracketKeyword_3_TimeoutKeyword_4_q_RightCurlyBracketKeyword_7____q = new AlternativeAlias(false, true, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getAndForkAccess().getAndKeyword_0()), new TokenAlias(false, false, grammarAccess.getAndForkAccess().getLeftCurlyBracketKeyword_2()), new TokenAlias(false, false, grammarAccess.getAndForkAccess().getRightCurlyBracketKeyword_4())), new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getTimerAccess().getTimerKeyword_1()), new TokenAlias(false, false, grammarAccess.getTimerAccess().getLeftCurlyBracketKeyword_3()), new TokenAlias(false, true, grammarAccess.getTimerAccess().getTimeoutKeyword_4()), new TokenAlias(false, false, grammarAccess.getTimerAccess().getRightCurlyBracketKeyword_7())), new TokenAlias(false, false, grammarAccess.getFailurePointAccess().getFailKeyword_0()), new TokenAlias(false, false, grammarAccess.getWaitingPlaceAccess().getWaitKeyword_1()));
		match_AndJoin_SyncKeyword_0_1_or_SynchKeyword_0_0_or_VerticalLineKeyword_0_2 = new AlternativeAlias(false, false, new TokenAlias(false, false, grammarAccess.getAndJoinAccess().getSyncKeyword_0_1()), new TokenAlias(false, false, grammarAccess.getAndJoinAccess().getSynchKeyword_0_0()), new TokenAlias(false, false, grammarAccess.getAndJoinAccess().getVerticalLineKeyword_0_2()));
		match_ComponentRef_ProtectedKeyword_0_q = new TokenAlias(false, true, grammarAccess.getComponentRefAccess().getProtectedKeyword_0());
		match_Condition___LeftCurlyBracketKeyword_3_0_RightCurlyBracketKeyword_3_2__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getConditionAccess().getLeftCurlyBracketKeyword_3_0()), new TokenAlias(false, false, grammarAccess.getConditionAccess().getRightCurlyBracketKeyword_3_2()));
		match_ContributionContext_IncludesKeyword_5_0_q = new TokenAlias(false, true, grammarAccess.getContributionContextAccess().getIncludesKeyword_5_0());
		match_EvaluationStrategy___IncludesKeyword_6_0_LeftCurlyBracketKeyword_6_1_RightCurlyBracketKeyword_6_3__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getEvaluationStrategyAccess().getIncludesKeyword_6_0()), new TokenAlias(false, false, grammarAccess.getEvaluationStrategyAccess().getLeftCurlyBracketKeyword_6_1()), new TokenAlias(false, false, grammarAccess.getEvaluationStrategyAccess().getRightCurlyBracketKeyword_6_3()));
		match_FailurePoint_Timer_WaitingPlace_FailKeyword_0_or_WaitKeyword_1_or___TimerKeyword_1_LeftCurlyBracketKeyword_3_TimeoutKeyword_4_q_RightCurlyBracketKeyword_7__ = new AlternativeAlias(false, false, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getTimerAccess().getTimerKeyword_1()), new TokenAlias(false, false, grammarAccess.getTimerAccess().getLeftCurlyBracketKeyword_3()), new TokenAlias(false, true, grammarAccess.getTimerAccess().getTimeoutKeyword_4()), new TokenAlias(false, false, grammarAccess.getTimerAccess().getRightCurlyBracketKeyword_7())), new TokenAlias(false, false, grammarAccess.getFailurePointAccess().getFailKeyword_0()), new TokenAlias(false, false, grammarAccess.getWaitingPlaceAccess().getWaitKeyword_1()));
		match_PathWithReferencedEnd_SemicolonKeyword_1_1_q = new TokenAlias(false, true, grammarAccess.getPathWithReferencedEndAccess().getSemicolonKeyword_1_1());
		match_Stub___LeftCurlyBracketKeyword_4_0_RightCurlyBracketKeyword_4_2__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getStubAccess().getLeftCurlyBracketKeyword_4_0()), new TokenAlias(false, false, grammarAccess.getStubAccess().getRightCurlyBracketKeyword_4_2()));
		match_Timer_TimeoutKeyword_4_q = new TokenAlias(false, true, grammarAccess.getTimerAccess().getTimeoutKeyword_4());
		match_Timer_WaitingPlace_WaitKeyword_1_or___TimerKeyword_1_LeftCurlyBracketKeyword_3_TimeoutKeyword_4_q_RightCurlyBracketKeyword_7__ = new AlternativeAlias(false, false, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getTimerAccess().getTimerKeyword_1()), new TokenAlias(false, false, grammarAccess.getTimerAccess().getLeftCurlyBracketKeyword_3()), new TokenAlias(false, true, grammarAccess.getTimerAccess().getTimeoutKeyword_4()), new TokenAlias(false, false, grammarAccess.getTimerAccess().getRightCurlyBracketKeyword_7())), new TokenAlias(false, false, grammarAccess.getWaitingPlaceAccess().getWaitKeyword_1()));
		match_URNspec___MetadataKeyword_11_0_LeftCurlyBracketKeyword_11_1_RightCurlyBracketKeyword_11_3__a = new GroupAlias(true, true, new TokenAlias(false, false, grammarAccess.getURNspecAccess().getMetadataKeyword_11_0()), new TokenAlias(false, false, grammarAccess.getURNspecAccess().getLeftCurlyBracketKeyword_11_1()), new TokenAlias(false, false, grammarAccess.getURNspecAccess().getRightCurlyBracketKeyword_11_3()));
		match_URNspec___MetadataKeyword_11_0_LeftCurlyBracketKeyword_11_1_RightCurlyBracketKeyword_11_3__p = new GroupAlias(true, false, new TokenAlias(false, false, grammarAccess.getURNspecAccess().getMetadataKeyword_11_0()), new TokenAlias(false, false, grammarAccess.getURNspecAccess().getLeftCurlyBracketKeyword_11_1()), new TokenAlias(false, false, grammarAccess.getURNspecAccess().getRightCurlyBracketKeyword_11_3()));
		match_URNspec___RightCurlyBracketKeyword_11_3_MetadataKeyword_11_0_LeftCurlyBracketKeyword_11_1__a = new GroupAlias(true, true, new TokenAlias(false, false, grammarAccess.getURNspecAccess().getRightCurlyBracketKeyword_11_3()), new TokenAlias(false, false, grammarAccess.getURNspecAccess().getMetadataKeyword_11_0()), new TokenAlias(false, false, grammarAccess.getURNspecAccess().getLeftCurlyBracketKeyword_11_1()));
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (ruleCall.getRule() == grammarAccess.getArrowRule())
			return getArrowToken(semanticObject, ruleCall, node);
		return "";
	}
	
	/**
	 * Arrow: '->';
	 */
	protected String getArrowToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "->";
	}
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_AndFork_EndPoint_FailurePoint_Timer_WaitingPlace_FailKeyword_0_or_WaitKeyword_1_or___AndKeyword_0_LeftCurlyBracketKeyword_2_RightCurlyBracketKeyword_4___or___EndKeyword_0_FullStopKeyword_3___or___TimerKeyword_1_LeftCurlyBracketKeyword_3_TimeoutKeyword_4_q_RightCurlyBracketKeyword_7__.equals(syntax))
				emit_AndFork_EndPoint_FailurePoint_Timer_WaitingPlace_FailKeyword_0_or_WaitKeyword_1_or___AndKeyword_0_LeftCurlyBracketKeyword_2_RightCurlyBracketKeyword_4___or___EndKeyword_0_FullStopKeyword_3___or___TimerKeyword_1_LeftCurlyBracketKeyword_3_TimeoutKeyword_4_q_RightCurlyBracketKeyword_7__(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_AndFork_FailurePoint_Timer_WaitingPlace___FailKeyword_0_or_WaitKeyword_1_or___AndKeyword_0_LeftCurlyBracketKeyword_2_RightCurlyBracketKeyword_4___or___TimerKeyword_1_LeftCurlyBracketKeyword_3_TimeoutKeyword_4_q_RightCurlyBracketKeyword_7____q.equals(syntax))
				emit_AndFork_FailurePoint_Timer_WaitingPlace___FailKeyword_0_or_WaitKeyword_1_or___AndKeyword_0_LeftCurlyBracketKeyword_2_RightCurlyBracketKeyword_4___or___TimerKeyword_1_LeftCurlyBracketKeyword_3_TimeoutKeyword_4_q_RightCurlyBracketKeyword_7____q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_AndJoin_SyncKeyword_0_1_or_SynchKeyword_0_0_or_VerticalLineKeyword_0_2.equals(syntax))
				emit_AndJoin_SyncKeyword_0_1_or_SynchKeyword_0_0_or_VerticalLineKeyword_0_2(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_ComponentRef_ProtectedKeyword_0_q.equals(syntax))
				emit_ComponentRef_ProtectedKeyword_0_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Condition___LeftCurlyBracketKeyword_3_0_RightCurlyBracketKeyword_3_2__q.equals(syntax))
				emit_Condition___LeftCurlyBracketKeyword_3_0_RightCurlyBracketKeyword_3_2__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_ContributionContext_IncludesKeyword_5_0_q.equals(syntax))
				emit_ContributionContext_IncludesKeyword_5_0_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_EvaluationStrategy___IncludesKeyword_6_0_LeftCurlyBracketKeyword_6_1_RightCurlyBracketKeyword_6_3__q.equals(syntax))
				emit_EvaluationStrategy___IncludesKeyword_6_0_LeftCurlyBracketKeyword_6_1_RightCurlyBracketKeyword_6_3__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_FailurePoint_Timer_WaitingPlace_FailKeyword_0_or_WaitKeyword_1_or___TimerKeyword_1_LeftCurlyBracketKeyword_3_TimeoutKeyword_4_q_RightCurlyBracketKeyword_7__.equals(syntax))
				emit_FailurePoint_Timer_WaitingPlace_FailKeyword_0_or_WaitKeyword_1_or___TimerKeyword_1_LeftCurlyBracketKeyword_3_TimeoutKeyword_4_q_RightCurlyBracketKeyword_7__(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_PathWithReferencedEnd_SemicolonKeyword_1_1_q.equals(syntax))
				emit_PathWithReferencedEnd_SemicolonKeyword_1_1_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Stub___LeftCurlyBracketKeyword_4_0_RightCurlyBracketKeyword_4_2__q.equals(syntax))
				emit_Stub___LeftCurlyBracketKeyword_4_0_RightCurlyBracketKeyword_4_2__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Timer_TimeoutKeyword_4_q.equals(syntax))
				emit_Timer_TimeoutKeyword_4_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Timer_WaitingPlace_WaitKeyword_1_or___TimerKeyword_1_LeftCurlyBracketKeyword_3_TimeoutKeyword_4_q_RightCurlyBracketKeyword_7__.equals(syntax))
				emit_Timer_WaitingPlace_WaitKeyword_1_or___TimerKeyword_1_LeftCurlyBracketKeyword_3_TimeoutKeyword_4_q_RightCurlyBracketKeyword_7__(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_URNspec___MetadataKeyword_11_0_LeftCurlyBracketKeyword_11_1_RightCurlyBracketKeyword_11_3__a.equals(syntax))
				emit_URNspec___MetadataKeyword_11_0_LeftCurlyBracketKeyword_11_1_RightCurlyBracketKeyword_11_3__a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_URNspec___MetadataKeyword_11_0_LeftCurlyBracketKeyword_11_1_RightCurlyBracketKeyword_11_3__p.equals(syntax))
				emit_URNspec___MetadataKeyword_11_0_LeftCurlyBracketKeyword_11_1_RightCurlyBracketKeyword_11_3__p(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_URNspec___RightCurlyBracketKeyword_11_3_MetadataKeyword_11_0_LeftCurlyBracketKeyword_11_1__a.equals(syntax))
				emit_URNspec___RightCurlyBracketKeyword_11_3_MetadataKeyword_11_0_LeftCurlyBracketKeyword_11_1__a(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     'wait' | ('timer' '{' 'timeout'? '}') | 'fail' | ('end' '.') | ('and' '{' '}')
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) (rule start)
	 */
	protected void emit_AndFork_EndPoint_FailurePoint_Timer_WaitingPlace_FailKeyword_0_or_WaitKeyword_1_or___AndKeyword_0_LeftCurlyBracketKeyword_2_RightCurlyBracketKeyword_4___or___EndKeyword_0_FullStopKeyword_3___or___TimerKeyword_1_LeftCurlyBracketKeyword_3_TimeoutKeyword_4_q_RightCurlyBracketKeyword_7__(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('wait' | ('timer' '{' 'timeout'? '}') | 'fail' | ('and' '{' '}'))?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) (rule start)
	 */
	protected void emit_AndFork_FailurePoint_Timer_WaitingPlace___FailKeyword_0_or_WaitKeyword_1_or___AndKeyword_0_LeftCurlyBracketKeyword_2_RightCurlyBracketKeyword_4___or___TimerKeyword_1_LeftCurlyBracketKeyword_3_TimeoutKeyword_4_q_RightCurlyBracketKeyword_7____q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     'synch' | 'sync' | '|'
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) name=QualifiedName
	 */
	protected void emit_AndJoin_SyncKeyword_0_1_or_SynchKeyword_0_0_or_VerticalLineKeyword_0_2(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     'protected'?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) kind=COMPONENTKIND
	 *     (rule start) (ambiguity) name=QualifiedName
	 */
	protected void emit_ComponentRef_ProtectedKeyword_0_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     expression=Text ']' (ambiguity) (rule end)
	 */
	protected void emit_Condition___LeftCurlyBracketKeyword_3_0_RightCurlyBracketKeyword_3_2__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     'includes'?
	 *
	 * This ambiguous syntax occurs at:
	 *     changes+=ContributionChange (ambiguity) '}' (rule end)
	 *     longName=LongName '{' (ambiguity) '}' (rule end)
	 */
	protected void emit_ContributionContext_IncludesKeyword_5_0_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('includes' '{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     evaluations+=Evaluation (ambiguity) '}' (rule end)
	 *     info=ConcreteStrategy (ambiguity) '}' (rule end)
	 *     longName=LongName '{' (ambiguity) '}' (rule end)
	 */
	protected void emit_EvaluationStrategy___IncludesKeyword_6_0_LeftCurlyBracketKeyword_6_1_RightCurlyBracketKeyword_6_3__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     'wait' | ('timer' '{' 'timeout'? '}') | 'fail'
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) (rule start)
	 */
	protected void emit_FailurePoint_Timer_WaitingPlace_FailKeyword_0_or_WaitKeyword_1_or___TimerKeyword_1_LeftCurlyBracketKeyword_3_TimeoutKeyword_4_q_RightCurlyBracketKeyword_7__(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ';'?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) Arrow (ambiguity) (rule start)
	 *     (rule start) Arrow (ambiguity) pathEnd=RegularEnd
	 *     index=PositiveInteger ';' (ambiguity) (rule end)
	 *     index=PositiveInteger ';' (ambiguity) pathEnd=RegularEnd
	 *     pathNodes+=PathBodyNode '->' (ambiguity) (rule end)
	 *     pathNodes+=PathBodyNode '->' (ambiguity) pathEnd=RegularEnd
	 */
	protected void emit_PathWithReferencedEnd_SemicolonKeyword_1_1_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     params=StubParameters (ambiguity) ';' connectingStubBody=PathBody
	 *     params=StubParameters (ambiguity) (rule end)
	 *     stubRef=[StubDeclaration|QualifiedName] (ambiguity) ';' connectingStubBody=PathBody
	 *     stubRef=[StubDeclaration|QualifiedName] (ambiguity) (rule end)
	 */
	protected void emit_Stub___LeftCurlyBracketKeyword_4_0_RightCurlyBracketKeyword_4_2__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     'timeout'?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) 'timer' '{' (ambiguity) '}' (rule start)
	 *     (rule start) 'timer' '{' (ambiguity) condition=Condition
	 *     (rule start) 'timer' '{' (ambiguity) timeoutPath=PathBody
	 *     kind=WAITKIND 'timer' '{' (ambiguity) '}' (rule end)
	 *     kind=WAITKIND 'timer' '{' (ambiguity) condition=Condition
	 *     kind=WAITKIND 'timer' '{' (ambiguity) timeoutPath=PathBody
	 *     longName=LongName '{' (ambiguity) '}' (rule end)
	 *     longName=LongName '{' (ambiguity) condition=Condition
	 *     longName=LongName '{' (ambiguity) timeoutPath=PathBody
	 */
	protected void emit_Timer_TimeoutKeyword_4_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     'wait' | ('timer' '{' 'timeout'? '}')
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) (rule start)
	 */
	protected void emit_Timer_WaitingPlace_WaitKeyword_1_or___TimerKeyword_1_LeftCurlyBracketKeyword_3_TimeoutKeyword_4_q_RightCurlyBracketKeyword_7__(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('metadata' '{' '}')*
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) 'urnModel' name=QualifiedName
	 *     (rule start) (ambiguity) (rule start)
	 *     (rule start) (ambiguity) actors+=Actor
	 *     (rule start) (ambiguity) concerns+=Concern
	 *     (rule start) (ambiguity) contribContextGroups+=ContributionContextGroup
	 *     (rule start) (ambiguity) contribContexts+=ContributionContext
	 *     (rule start) (ambiguity) indConversions+=IndicatorConversion
	 *     (rule start) (ambiguity) showAsMeansEnd?='showAsMeansEnd'
	 *     (rule start) (ambiguity) stratGroups+=StrategiesGroup
	 *     (rule start) (ambiguity) strategies+=EvaluationStrategy
	 *     (rule start) (ambiguity) ucmMaps+=UCMmap
	 *     (rule start) (ambiguity) urnlinks+=URNlink
	 *     actors+=Actor (ambiguity) 'urnModel' name=QualifiedName
	 *     actors+=Actor (ambiguity) (rule end)
	 *     actors+=Actor (ambiguity) actors+=Actor
	 *     actors+=Actor (ambiguity) concerns+=Concern
	 *     actors+=Actor (ambiguity) contribContextGroups+=ContributionContextGroup
	 *     actors+=Actor (ambiguity) contribContexts+=ContributionContext
	 *     actors+=Actor (ambiguity) indConversions+=IndicatorConversion
	 *     actors+=Actor (ambiguity) showAsMeansEnd?='showAsMeansEnd'
	 *     actors+=Actor (ambiguity) stratGroups+=StrategiesGroup
	 *     actors+=Actor (ambiguity) strategies+=EvaluationStrategy
	 *     actors+=Actor (ambiguity) ucmMaps+=UCMmap
	 *     actors+=Actor (ambiguity) urnlinks+=URNlink
	 *     concerns+=Concern (ambiguity) 'urnModel' name=QualifiedName
	 *     concerns+=Concern (ambiguity) (rule end)
	 *     concerns+=Concern (ambiguity) actors+=Actor
	 *     concerns+=Concern (ambiguity) concerns+=Concern
	 *     concerns+=Concern (ambiguity) contribContextGroups+=ContributionContextGroup
	 *     concerns+=Concern (ambiguity) contribContexts+=ContributionContext
	 *     concerns+=Concern (ambiguity) indConversions+=IndicatorConversion
	 *     concerns+=Concern (ambiguity) showAsMeansEnd?='showAsMeansEnd'
	 *     concerns+=Concern (ambiguity) stratGroups+=StrategiesGroup
	 *     concerns+=Concern (ambiguity) strategies+=EvaluationStrategy
	 *     concerns+=Concern (ambiguity) ucmMaps+=UCMmap
	 *     concerns+=Concern (ambiguity) urnlinks+=URNlink
	 *     contribContextGroups+=ContributionContextGroup (ambiguity) 'urnModel' name=QualifiedName
	 *     contribContextGroups+=ContributionContextGroup (ambiguity) (rule end)
	 *     contribContextGroups+=ContributionContextGroup (ambiguity) actors+=Actor
	 *     contribContextGroups+=ContributionContextGroup (ambiguity) concerns+=Concern
	 *     contribContextGroups+=ContributionContextGroup (ambiguity) contribContextGroups+=ContributionContextGroup
	 *     contribContextGroups+=ContributionContextGroup (ambiguity) contribContexts+=ContributionContext
	 *     contribContextGroups+=ContributionContextGroup (ambiguity) indConversions+=IndicatorConversion
	 *     contribContextGroups+=ContributionContextGroup (ambiguity) showAsMeansEnd?='showAsMeansEnd'
	 *     contribContextGroups+=ContributionContextGroup (ambiguity) stratGroups+=StrategiesGroup
	 *     contribContextGroups+=ContributionContextGroup (ambiguity) strategies+=EvaluationStrategy
	 *     contribContextGroups+=ContributionContextGroup (ambiguity) ucmMaps+=UCMmap
	 *     contribContextGroups+=ContributionContextGroup (ambiguity) urnlinks+=URNlink
	 *     contribContexts+=ContributionContext (ambiguity) 'urnModel' name=QualifiedName
	 *     contribContexts+=ContributionContext (ambiguity) (rule end)
	 *     contribContexts+=ContributionContext (ambiguity) actors+=Actor
	 *     contribContexts+=ContributionContext (ambiguity) concerns+=Concern
	 *     contribContexts+=ContributionContext (ambiguity) contribContextGroups+=ContributionContextGroup
	 *     contribContexts+=ContributionContext (ambiguity) contribContexts+=ContributionContext
	 *     contribContexts+=ContributionContext (ambiguity) indConversions+=IndicatorConversion
	 *     contribContexts+=ContributionContext (ambiguity) showAsMeansEnd?='showAsMeansEnd'
	 *     contribContexts+=ContributionContext (ambiguity) stratGroups+=StrategiesGroup
	 *     contribContexts+=ContributionContext (ambiguity) strategies+=EvaluationStrategy
	 *     contribContexts+=ContributionContext (ambiguity) ucmMaps+=UCMmap
	 *     contribContexts+=ContributionContext (ambiguity) urnlinks+=URNlink
	 *     indConversions+=IndicatorConversion (ambiguity) 'urnModel' name=QualifiedName
	 *     indConversions+=IndicatorConversion (ambiguity) (rule end)
	 *     indConversions+=IndicatorConversion (ambiguity) actors+=Actor
	 *     indConversions+=IndicatorConversion (ambiguity) concerns+=Concern
	 *     indConversions+=IndicatorConversion (ambiguity) contribContextGroups+=ContributionContextGroup
	 *     indConversions+=IndicatorConversion (ambiguity) contribContexts+=ContributionContext
	 *     indConversions+=IndicatorConversion (ambiguity) indConversions+=IndicatorConversion
	 *     indConversions+=IndicatorConversion (ambiguity) showAsMeansEnd?='showAsMeansEnd'
	 *     indConversions+=IndicatorConversion (ambiguity) stratGroups+=StrategiesGroup
	 *     indConversions+=IndicatorConversion (ambiguity) strategies+=EvaluationStrategy
	 *     indConversions+=IndicatorConversion (ambiguity) ucmMaps+=UCMmap
	 *     indConversions+=IndicatorConversion (ambiguity) urnlinks+=URNlink
	 *     info=ConcreteURNspec (ambiguity) 'urnModel' name=QualifiedName
	 *     info=ConcreteURNspec (ambiguity) (rule end)
	 *     info=ConcreteURNspec (ambiguity) actors+=Actor
	 *     info=ConcreteURNspec (ambiguity) concerns+=Concern
	 *     info=ConcreteURNspec (ambiguity) contribContextGroups+=ContributionContextGroup
	 *     info=ConcreteURNspec (ambiguity) contribContexts+=ContributionContext
	 *     info=ConcreteURNspec (ambiguity) indConversions+=IndicatorConversion
	 *     info=ConcreteURNspec (ambiguity) showAsMeansEnd?='showAsMeansEnd'
	 *     info=ConcreteURNspec (ambiguity) stratGroups+=StrategiesGroup
	 *     info=ConcreteURNspec (ambiguity) strategies+=EvaluationStrategy
	 *     info=ConcreteURNspec (ambiguity) ucmMaps+=UCMmap
	 *     info=ConcreteURNspec (ambiguity) urnlinks+=URNlink
	 *     metadata+=Metadata '}' (ambiguity) 'urnModel' name=QualifiedName
	 *     metadata+=Metadata '}' (ambiguity) (rule end)
	 *     metadata+=Metadata '}' (ambiguity) actors+=Actor
	 *     metadata+=Metadata '}' (ambiguity) concerns+=Concern
	 *     metadata+=Metadata '}' (ambiguity) contribContextGroups+=ContributionContextGroup
	 *     metadata+=Metadata '}' (ambiguity) contribContexts+=ContributionContext
	 *     metadata+=Metadata '}' (ambiguity) indConversions+=IndicatorConversion
	 *     metadata+=Metadata '}' (ambiguity) showAsMeansEnd?='showAsMeansEnd'
	 *     metadata+=Metadata '}' (ambiguity) stratGroups+=StrategiesGroup
	 *     metadata+=Metadata '}' (ambiguity) strategies+=EvaluationStrategy
	 *     metadata+=Metadata '}' (ambiguity) ucmMaps+=UCMmap
	 *     metadata+=Metadata '}' (ambiguity) urnlinks+=URNlink
	 *     name=QualifiedName (ambiguity) 'urnModel' name=QualifiedName
	 *     name=QualifiedName (ambiguity) (rule end)
	 *     name=QualifiedName (ambiguity) actors+=Actor
	 *     name=QualifiedName (ambiguity) concerns+=Concern
	 *     name=QualifiedName (ambiguity) contribContextGroups+=ContributionContextGroup
	 *     name=QualifiedName (ambiguity) contribContexts+=ContributionContext
	 *     name=QualifiedName (ambiguity) indConversions+=IndicatorConversion
	 *     name=QualifiedName (ambiguity) showAsMeansEnd?='showAsMeansEnd'
	 *     name=QualifiedName (ambiguity) stratGroups+=StrategiesGroup
	 *     name=QualifiedName (ambiguity) strategies+=EvaluationStrategy
	 *     name=QualifiedName (ambiguity) ucmMaps+=UCMmap
	 *     name=QualifiedName (ambiguity) urnlinks+=URNlink
	 *     showAsMeansEnd?='showAsMeansEnd' (ambiguity) 'urnModel' name=QualifiedName
	 *     showAsMeansEnd?='showAsMeansEnd' (ambiguity) (rule end)
	 *     showAsMeansEnd?='showAsMeansEnd' (ambiguity) actors+=Actor
	 *     showAsMeansEnd?='showAsMeansEnd' (ambiguity) concerns+=Concern
	 *     showAsMeansEnd?='showAsMeansEnd' (ambiguity) contribContextGroups+=ContributionContextGroup
	 *     showAsMeansEnd?='showAsMeansEnd' (ambiguity) contribContexts+=ContributionContext
	 *     showAsMeansEnd?='showAsMeansEnd' (ambiguity) indConversions+=IndicatorConversion
	 *     showAsMeansEnd?='showAsMeansEnd' (ambiguity) showAsMeansEnd?='showAsMeansEnd'
	 *     showAsMeansEnd?='showAsMeansEnd' (ambiguity) stratGroups+=StrategiesGroup
	 *     showAsMeansEnd?='showAsMeansEnd' (ambiguity) strategies+=EvaluationStrategy
	 *     showAsMeansEnd?='showAsMeansEnd' (ambiguity) ucmMaps+=UCMmap
	 *     showAsMeansEnd?='showAsMeansEnd' (ambiguity) urnlinks+=URNlink
	 *     stratGroups+=StrategiesGroup (ambiguity) 'urnModel' name=QualifiedName
	 *     stratGroups+=StrategiesGroup (ambiguity) (rule end)
	 *     stratGroups+=StrategiesGroup (ambiguity) actors+=Actor
	 *     stratGroups+=StrategiesGroup (ambiguity) concerns+=Concern
	 *     stratGroups+=StrategiesGroup (ambiguity) contribContextGroups+=ContributionContextGroup
	 *     stratGroups+=StrategiesGroup (ambiguity) contribContexts+=ContributionContext
	 *     stratGroups+=StrategiesGroup (ambiguity) indConversions+=IndicatorConversion
	 *     stratGroups+=StrategiesGroup (ambiguity) showAsMeansEnd?='showAsMeansEnd'
	 *     stratGroups+=StrategiesGroup (ambiguity) stratGroups+=StrategiesGroup
	 *     stratGroups+=StrategiesGroup (ambiguity) strategies+=EvaluationStrategy
	 *     stratGroups+=StrategiesGroup (ambiguity) ucmMaps+=UCMmap
	 *     stratGroups+=StrategiesGroup (ambiguity) urnlinks+=URNlink
	 *     strategies+=EvaluationStrategy (ambiguity) 'urnModel' name=QualifiedName
	 *     strategies+=EvaluationStrategy (ambiguity) (rule end)
	 *     strategies+=EvaluationStrategy (ambiguity) actors+=Actor
	 *     strategies+=EvaluationStrategy (ambiguity) concerns+=Concern
	 *     strategies+=EvaluationStrategy (ambiguity) contribContextGroups+=ContributionContextGroup
	 *     strategies+=EvaluationStrategy (ambiguity) contribContexts+=ContributionContext
	 *     strategies+=EvaluationStrategy (ambiguity) indConversions+=IndicatorConversion
	 *     strategies+=EvaluationStrategy (ambiguity) showAsMeansEnd?='showAsMeansEnd'
	 *     strategies+=EvaluationStrategy (ambiguity) stratGroups+=StrategiesGroup
	 *     strategies+=EvaluationStrategy (ambiguity) strategies+=EvaluationStrategy
	 *     strategies+=EvaluationStrategy (ambiguity) ucmMaps+=UCMmap
	 *     strategies+=EvaluationStrategy (ambiguity) urnlinks+=URNlink
	 *     ucmMaps+=UCMmap (ambiguity) 'urnModel' name=QualifiedName
	 *     ucmMaps+=UCMmap (ambiguity) (rule end)
	 *     ucmMaps+=UCMmap (ambiguity) actors+=Actor
	 *     ucmMaps+=UCMmap (ambiguity) concerns+=Concern
	 *     ucmMaps+=UCMmap (ambiguity) contribContextGroups+=ContributionContextGroup
	 *     ucmMaps+=UCMmap (ambiguity) contribContexts+=ContributionContext
	 *     ucmMaps+=UCMmap (ambiguity) indConversions+=IndicatorConversion
	 *     ucmMaps+=UCMmap (ambiguity) showAsMeansEnd?='showAsMeansEnd'
	 *     ucmMaps+=UCMmap (ambiguity) stratGroups+=StrategiesGroup
	 *     ucmMaps+=UCMmap (ambiguity) strategies+=EvaluationStrategy
	 *     ucmMaps+=UCMmap (ambiguity) ucmMaps+=UCMmap
	 *     ucmMaps+=UCMmap (ambiguity) urnlinks+=URNlink
	 *     urnlinks+=URNlink (ambiguity) 'urnModel' name=QualifiedName
	 *     urnlinks+=URNlink (ambiguity) (rule end)
	 *     urnlinks+=URNlink (ambiguity) actors+=Actor
	 *     urnlinks+=URNlink (ambiguity) concerns+=Concern
	 *     urnlinks+=URNlink (ambiguity) contribContextGroups+=ContributionContextGroup
	 *     urnlinks+=URNlink (ambiguity) contribContexts+=ContributionContext
	 *     urnlinks+=URNlink (ambiguity) indConversions+=IndicatorConversion
	 *     urnlinks+=URNlink (ambiguity) showAsMeansEnd?='showAsMeansEnd'
	 *     urnlinks+=URNlink (ambiguity) stratGroups+=StrategiesGroup
	 *     urnlinks+=URNlink (ambiguity) strategies+=EvaluationStrategy
	 *     urnlinks+=URNlink (ambiguity) ucmMaps+=UCMmap
	 *     urnlinks+=URNlink (ambiguity) urnlinks+=URNlink
	 */
	protected void emit_URNspec___MetadataKeyword_11_0_LeftCurlyBracketKeyword_11_1_RightCurlyBracketKeyword_11_3__a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('metadata' '{' '}')+
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) (rule start)
	 */
	protected void emit_URNspec___MetadataKeyword_11_0_LeftCurlyBracketKeyword_11_1_RightCurlyBracketKeyword_11_3__p(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('}' 'metadata' '{')*
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) 'metadata' '{' (ambiguity) metadata+=Metadata
	 *     actors+=Actor 'metadata' '{' (ambiguity) metadata+=Metadata
	 *     concerns+=Concern 'metadata' '{' (ambiguity) metadata+=Metadata
	 *     contribContextGroups+=ContributionContextGroup 'metadata' '{' (ambiguity) metadata+=Metadata
	 *     contribContexts+=ContributionContext 'metadata' '{' (ambiguity) metadata+=Metadata
	 *     indConversions+=IndicatorConversion 'metadata' '{' (ambiguity) metadata+=Metadata
	 *     info=ConcreteURNspec 'metadata' '{' (ambiguity) metadata+=Metadata
	 *     metadata+=Metadata (ambiguity) metadata+=Metadata
	 *     name=QualifiedName 'metadata' '{' (ambiguity) metadata+=Metadata
	 *     showAsMeansEnd?='showAsMeansEnd' 'metadata' '{' (ambiguity) metadata+=Metadata
	 *     stratGroups+=StrategiesGroup 'metadata' '{' (ambiguity) metadata+=Metadata
	 *     strategies+=EvaluationStrategy 'metadata' '{' (ambiguity) metadata+=Metadata
	 *     ucmMaps+=UCMmap 'metadata' '{' (ambiguity) metadata+=Metadata
	 *     urnlinks+=URNlink 'metadata' '{' (ambiguity) metadata+=Metadata
	 */
	protected void emit_URNspec___RightCurlyBracketKeyword_11_3_MetadataKeyword_11_0_LeftCurlyBracketKeyword_11_1__a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
