/**
 * generated by Xtext 2.15.0-SNAPSHOT
 */
package org.xtext.example.mydsl.tURN;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Concrete UR Nspec</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.tURN.ConcreteURNspec#getDescription <em>Description</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.tURN.ConcreteURNspec#getAuthor <em>Author</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.tURN.ConcreteURNspec#getCreated <em>Created</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.tURN.ConcreteURNspec#getModified <em>Modified</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.tURN.ConcreteURNspec#getSpecVersion <em>Spec Version</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.tURN.ConcreteURNspec#getUrnVersion <em>Urn Version</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.tURN.TURNPackage#getConcreteURNspec()
 * @model
 * @generated
 */
public interface ConcreteURNspec extends EObject
{
  /**
   * Returns the value of the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Description</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Description</em>' attribute.
   * @see #setDescription(String)
   * @see org.xtext.example.mydsl.tURN.TURNPackage#getConcreteURNspec_Description()
   * @model
   * @generated
   */
  String getDescription();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.tURN.ConcreteURNspec#getDescription <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Description</em>' attribute.
   * @see #getDescription()
   * @generated
   */
  void setDescription(String value);

  /**
   * Returns the value of the '<em><b>Author</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Author</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Author</em>' attribute.
   * @see #setAuthor(String)
   * @see org.xtext.example.mydsl.tURN.TURNPackage#getConcreteURNspec_Author()
   * @model
   * @generated
   */
  String getAuthor();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.tURN.ConcreteURNspec#getAuthor <em>Author</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Author</em>' attribute.
   * @see #getAuthor()
   * @generated
   */
  void setAuthor(String value);

  /**
   * Returns the value of the '<em><b>Created</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Created</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Created</em>' attribute.
   * @see #setCreated(String)
   * @see org.xtext.example.mydsl.tURN.TURNPackage#getConcreteURNspec_Created()
   * @model
   * @generated
   */
  String getCreated();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.tURN.ConcreteURNspec#getCreated <em>Created</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Created</em>' attribute.
   * @see #getCreated()
   * @generated
   */
  void setCreated(String value);

  /**
   * Returns the value of the '<em><b>Modified</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Modified</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Modified</em>' attribute.
   * @see #setModified(String)
   * @see org.xtext.example.mydsl.tURN.TURNPackage#getConcreteURNspec_Modified()
   * @model
   * @generated
   */
  String getModified();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.tURN.ConcreteURNspec#getModified <em>Modified</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Modified</em>' attribute.
   * @see #getModified()
   * @generated
   */
  void setModified(String value);

  /**
   * Returns the value of the '<em><b>Spec Version</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Spec Version</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Spec Version</em>' attribute.
   * @see #setSpecVersion(String)
   * @see org.xtext.example.mydsl.tURN.TURNPackage#getConcreteURNspec_SpecVersion()
   * @model
   * @generated
   */
  String getSpecVersion();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.tURN.ConcreteURNspec#getSpecVersion <em>Spec Version</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Spec Version</em>' attribute.
   * @see #getSpecVersion()
   * @generated
   */
  void setSpecVersion(String value);

  /**
   * Returns the value of the '<em><b>Urn Version</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Urn Version</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Urn Version</em>' attribute.
   * @see #setUrnVersion(String)
   * @see org.xtext.example.mydsl.tURN.TURNPackage#getConcreteURNspec_UrnVersion()
   * @model
   * @generated
   */
  String getUrnVersion();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.tURN.ConcreteURNspec#getUrnVersion <em>Urn Version</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Urn Version</em>' attribute.
   * @see #getUrnVersion()
   * @generated
   */
  void setUrnVersion(String value);

} // ConcreteURNspec
