/**
 * generated by Xtext 2.15.0-SNAPSHOT
 */
package org.xtext.example.mydsl.tURN;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Contribution Change</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.tURN.ContributionChange#getContribution <em>Contribution</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.tURN.ContributionChange#getNewContribution <em>New Contribution</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.tURN.ContributionChange#getNewQuantitativeContribution <em>New Quantitative Contribution</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.tURN.TURNPackage#getContributionChange()
 * @model
 * @generated
 */
public interface ContributionChange extends EObject
{
  /**
   * Returns the value of the '<em><b>Contribution</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Contribution</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Contribution</em>' reference.
   * @see #setContribution(Contribution)
   * @see org.xtext.example.mydsl.tURN.TURNPackage#getContributionChange_Contribution()
   * @model
   * @generated
   */
  Contribution getContribution();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.tURN.ContributionChange#getContribution <em>Contribution</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Contribution</em>' reference.
   * @see #getContribution()
   * @generated
   */
  void setContribution(Contribution value);

  /**
   * Returns the value of the '<em><b>New Contribution</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.example.mydsl.tURN.ContributionType}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>New Contribution</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>New Contribution</em>' attribute.
   * @see org.xtext.example.mydsl.tURN.ContributionType
   * @see #setNewContribution(ContributionType)
   * @see org.xtext.example.mydsl.tURN.TURNPackage#getContributionChange_NewContribution()
   * @model
   * @generated
   */
  ContributionType getNewContribution();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.tURN.ContributionChange#getNewContribution <em>New Contribution</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>New Contribution</em>' attribute.
   * @see org.xtext.example.mydsl.tURN.ContributionType
   * @see #getNewContribution()
   * @generated
   */
  void setNewContribution(ContributionType value);

  /**
   * Returns the value of the '<em><b>New Quantitative Contribution</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>New Quantitative Contribution</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>New Quantitative Contribution</em>' attribute.
   * @see #setNewQuantitativeContribution(int)
   * @see org.xtext.example.mydsl.tURN.TURNPackage#getContributionChange_NewQuantitativeContribution()
   * @model
   * @generated
   */
  int getNewQuantitativeContribution();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.tURN.ContributionChange#getNewQuantitativeContribution <em>New Quantitative Contribution</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>New Quantitative Contribution</em>' attribute.
   * @see #getNewQuantitativeContribution()
   * @generated
   */
  void setNewQuantitativeContribution(int value);

} // ContributionChange
