/**
 * generated by Xtext 2.15.0-SNAPSHOT
 */
package org.xtext.example.mydsl.tURN;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Path Body Node</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.tURN.TURNPackage#getPathBodyNode()
 * @model
 * @generated
 */
public interface PathBodyNode extends ReferencedBoundElement
{
} // PathBodyNode
