/**
 * generated by Xtext 2.15.0-SNAPSHOT
 */
package org.xtext.example.mydsl.tURN;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Regular End</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.tURN.TURNPackage#getRegularEnd()
 * @model
 * @generated
 */
public interface RegularEnd extends ReferencedBoundElement
{
} // RegularEnd
