/**
 * generated by Xtext 2.15.0-SNAPSHOT
 */
package org.xtext.example.mydsl.tURN;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Start Point</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.tURN.StartPoint#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.tURN.StartPoint#getLongName <em>Long Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.tURN.StartPoint#getFailKind <em>Fail Kind</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.tURN.StartPoint#getCatches <em>Catches</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.tURN.StartPoint#getPrecondition <em>Precondition</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.tURN.TURNPackage#getStartPoint()
 * @model
 * @generated
 */
public interface StartPoint extends ConnectElement, ReferencedBoundElement
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.mydsl.tURN.TURNPackage#getStartPoint_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.tURN.StartPoint#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Long Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Long Name</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Long Name</em>' containment reference.
   * @see #setLongName(LongName)
   * @see org.xtext.example.mydsl.tURN.TURNPackage#getStartPoint_LongName()
   * @model containment="true"
   * @generated
   */
  LongName getLongName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.tURN.StartPoint#getLongName <em>Long Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Long Name</em>' containment reference.
   * @see #getLongName()
   * @generated
   */
  void setLongName(LongName value);

  /**
   * Returns the value of the '<em><b>Fail Kind</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Fail Kind</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fail Kind</em>' attribute.
   * @see #setFailKind(String)
   * @see org.xtext.example.mydsl.tURN.TURNPackage#getStartPoint_FailKind()
   * @model
   * @generated
   */
  String getFailKind();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.tURN.StartPoint#getFailKind <em>Fail Kind</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Fail Kind</em>' attribute.
   * @see #getFailKind()
   * @generated
   */
  void setFailKind(String value);

  /**
   * Returns the value of the '<em><b>Catches</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Catches</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Catches</em>' attribute.
   * @see #setCatches(String)
   * @see org.xtext.example.mydsl.tURN.TURNPackage#getStartPoint_Catches()
   * @model
   * @generated
   */
  String getCatches();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.tURN.StartPoint#getCatches <em>Catches</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Catches</em>' attribute.
   * @see #getCatches()
   * @generated
   */
  void setCatches(String value);

  /**
   * Returns the value of the '<em><b>Precondition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Precondition</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Precondition</em>' containment reference.
   * @see #setPrecondition(Condition)
   * @see org.xtext.example.mydsl.tURN.TURNPackage#getStartPoint_Precondition()
   * @model containment="true"
   * @generated
   */
  Condition getPrecondition();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.tURN.StartPoint#getPrecondition <em>Precondition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Precondition</em>' containment reference.
   * @see #getPrecondition()
   * @generated
   */
  void setPrecondition(Condition value);

} // StartPoint
