/**
 * generated by Xtext 2.15.0-SNAPSHOT
 */
package org.xtext.example.mydsl.tURN;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>UR Nmodel Element</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.tURN.TURNPackage#getURNmodelElement()
 * @model
 * @generated
 */
public interface URNmodelElement extends EObject
{
} // URNmodelElement
