/*
 * generated by Xtext 2.15.0-SNAPSHOT
 */
package org.xtext.example.mydsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.mydsl.parser.antlr.internal.InternalTURNParser;
import org.xtext.example.mydsl.services.TURNGrammarAccess;

public class TURNParser extends AbstractAntlrParser {

	@Inject
	private TURNGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalTURNParser createParser(XtextTokenStream stream) {
		return new InternalTURNParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "URNspec";
	}

	public TURNGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(TURNGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
