/*
 * generated by Xtext 2.12.0
 */
package mcgill.xtext.turn.scoping

import org.xtext.example.mydsl.scoping.AbstractTURNScopeProvider

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
class TURNQualifiedNameProvider extends AbstractTURNScopeProvider {

}
