/*
 * generated by Xtext 2.15.0-SNAPSHOT
 */
package org.xtext.example.mydsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class TURNStandaloneSetup extends TURNStandaloneSetupGenerated {

	def static void doSetup() {
		new TURNStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
