/**
 * generated by Xtext 2.15.0-SNAPSHOT
 */
package org.xtext.example.mydsl.tURN.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.mydsl.tURN.PathBodyNode;
import org.xtext.example.mydsl.tURN.TURNPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Path Body Node</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class PathBodyNodeImpl extends ReferencedBoundElementImpl implements PathBodyNode
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PathBodyNodeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return TURNPackage.Literals.PATH_BODY_NODE;
  }

} //PathBodyNodeImpl
